/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-03-16 13:17:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.laptrinhweb.util.SecurityUtils;

public final class checkout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/E:/bookshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/bookweb/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1437576592000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1615455422135L));
    _jspx_dependants.put("jar:file:/E:/bookshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/bookweb/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-3.2.8.RELEASE.jar", Long.valueOf(1614783391670L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1614783475869L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar", Long.valueOf(1614783217951L));
    _jspx_dependants.put("jar:file:/E:/bookshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/bookweb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/E:/bookshop/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/bookweb/WEB-INF/lib/spring-webmvc-4.3.13.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511752906000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1614783441906L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.laptrinhweb.util.SecurityUtils");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("       <!-- Start Bradcaump area -->\r\n");
      out.write("        <div class=\"ht__bradcaump__area bg-image--4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"bradcaump__inner text-center\">\r\n");
      out.write("                        \t<h2 class=\"bradcaump-title\">Checkout</h2>\r\n");
      out.write("                            <nav class=\"bradcaump-content\">\r\n");
      out.write("                              <a class=\"breadcrumb_item\" href=\"index.html\">Home</a>\r\n");
      out.write("                              <span class=\"brd-separetor\">/</span>\r\n");
      out.write("                              <span class=\"breadcrumb_item active\">Checkout</span>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Bradcaump area -->\r\n");
      out.write("        <!-- Start Checkout Area -->\r\n");
      out.write("        <section class=\"wn__checkout__area section-padding--lg bg__white\">\r\n");
      out.write("        \t<div class=\"container\">\r\n");
      out.write("        \t\t<div class=\"row\">\r\n");
      out.write("        \t\t\t<div class=\"col-lg-6 col-12\">\r\n");
      out.write("        \t\t\t\t<div class=\"customer_details\">\r\n");
      out.write("        \t\t\t\t\t<h3>Billing details</h3>\r\n");
      out.write("        \t\t\t\t\t<div class=\"customar__field\">\r\n");
      out.write("        \t\t\t\t\t\t<div class=\"input_box\">\r\n");
      out.write("        \t\t\t\t\t\t\t<label>Address <span></span></label>\r\n");
      out.write("        \t\t\t\t\t\t\t<input id=\"address\" type=\"text\" placeholder=\"Street address\">\r\n");
      out.write("        \t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t<div class=\"input_box\">\r\n");
      out.write("        \t\t\t\t\t\t\t<label>Note <span>*</span></label>\r\n");
      out.write("        \t\t\t\t\t\t\t<textarea id=\"note\"  type=\"text\" placeholder=\"Note address\" style=\"height: 300px;width: 600px;\"></textarea>\r\n");
      out.write("        \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("        \t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\r\n");
      out.write("        \t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("        \t\t\t<div class=\"col-lg-6 col-12 md-mt-40 sm-mt-40\">\r\n");
      out.write("        \t\t\t\t<div class=\"wn__order__box\">\r\n");
      out.write("        \t\t\t\t\t<h3 class=\"onder__title\">Your order</h3>\r\n");
      out.write("        \t\t\t\t\t<ul class=\"order__total\">\r\n");
      out.write("        \t\t\t\t\t\t<li>Product</li>\r\n");
      out.write("        \t\t\t\t\t\t<li>Total</li>\r\n");
      out.write("        \t\t\t\t\t</ul>\r\n");
      out.write("        \t\t\t\t\t<ul class=\"order_product\">\r\n");
      out.write("        \t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("        \t\t\t\t\t</ul>\r\n");
      out.write("        \t\t\t\t\t<ul class=\"total__amount\">\r\n");
      out.write("        \t\t\t\t\t\t<li>Order Total <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("đ</span></li>\r\n");
      out.write("        \t\t\t\t\t</ul>\r\n");
      out.write("        \t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t    <div id=\"accordion\" class=\"checkout_accordion mt--30\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t\t    <div class=\"payment\">\r\n");
      out.write("\t\t\t\t\t\t        <div class=\"che__header\" role=\"tab\" id=\"headingOne\" >\r\n");
      out.write("\t\t\t\t\t\t          \t<a id=\"btnCheckout\" class=\"checkout__title\" href=\"#\" style=\"background-color: orangered;color: #fff;text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t                <span >Mua hàng</span>\r\n");
      out.write("\t\t\t\t\t\t          \t</a>\r\n");
      out.write("\t\t\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- End Checkout Area -->\r\n");
      out.write("        <script>\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("    \t\t$('#btnCheckout').click(function(e){\r\n");
      out.write("    \t\t\te.preventDefault();\r\n");
      out.write("    \t\t\tvar formData  = new FormData();\r\n");
      out.write("    \t\t\tformData.append('deliveryAddress',$('#address').val());\r\n");
      out.write("    \t\t\tformData.append('note',$('#note').val());\r\n");
      out.write("    \t\t\tvar data={};\r\n");
      out.write("    \t        for(var item of formData.entries()){\r\n");
      out.write("    \t            data[\"\"+item[0]+\"\"] =item[1];\r\n");
      out.write("    \t        }\r\n");
      out.write("    \t        addCheckout(data);\r\n");
      out.write("    \t\t})\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\tfunction addCheckout(data){\r\n");
      out.write("    \t\t\t$.ajax({\r\n");
      out.write("    \t\t\t\turl:'/api/order/checkout_order',\r\n");
      out.write("    \t\t\t\ttype:'POST',\r\n");
      out.write("    \t\t\t\tdataType : 'json',\r\n");
      out.write("            \t\tcontentType: 'application/json',\r\n");
      out.write("    \t\t\t\tdata : JSON.stringify(data),\r\n");
      out.write("    \t\t\t\tsuccess: function(){\r\n");
      out.write("    \t\t\t\t\tswal(\"\", \"Đặt hàng thành công\", \"success\");\r\n");
      out.write("    \t\t\t\t\tsetTimeout(redirect,1500);\r\n");
      out.write("    \t\t\t\t},\r\n");
      out.write("    \t\t\t\terror : function(){\r\n");
      out.write("    \t\t\t\t\tswal(\"\", \"Đặt hàng không thành công\", \"error\");\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t})\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\tfunction redirect(){\r\n");
      out.write("    \t\t\twindow.location.href = \"/shop?page=1\";\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t})\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/web/checkout.jsp(60,13) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("entry");
      // /WEB-INF/views/web/checkout.jsp(60,13) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/web/checkout.jsp(60,13) '${myCart}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${myCart}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        \t\t\t\t\t\t<tr>\r\n");
            out.write("                                    <li>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.value.bookDTO.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('x');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.value.quantity}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" <span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.value.quantity*entry.value.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></li>\r\n");
            out.write("                                 </tr>\r\n");
            out.write("        \t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
