/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-03-16 13:02:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.laptrinhweb.util.SecurityUtils;

public final class product_005fdetails_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.laptrinhweb.util.SecurityUtils");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("         <!-- Start Bradcaump area -->\r\n");
      out.write("        <div class=\"ht__bradcaump__area bg-image--4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-12\">\r\n");
      out.write("                        <div class=\"bradcaump__inner text-center\">\r\n");
      out.write("                        \t<h2 class=\"bradcaump-title\">Shop Single</h2>\r\n");
      out.write("                            <nav class=\"bradcaump-content\">\r\n");
      out.write("                              <a class=\"breadcrumb_item\" href=\"index.html\">Home</a>\r\n");
      out.write("                              <span class=\"brd-separetor\">/</span>\r\n");
      out.write("                              <span class=\"breadcrumb_item active\">Shop Single</span>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Bradcaump area -->\r\n");
      out.write("        <!-- Start main Content -->\r\n");
      out.write("        <div class=\"maincontent bg--white pt--80 pb--55\">\r\n");
      out.write("        \t<div class=\"container\">\r\n");
      out.write("        \t\t<div class=\"row\">\r\n");
      out.write("        \t\t\t<div class=\"col-lg-10 col-12\">\r\n");
      out.write("        \t\t\t\t<div class=\"wn__single__product\">\r\n");
      out.write("        \t\t\t\t\t<div class=\"row\">\r\n");
      out.write("        \t\t\t\t\t\t<div class=\"col-lg-6 col-12\">\r\n");
      out.write("        \t\t\t\t\t\t\t<div class=\"wn__fotorama__wrapper\">\r\n");
      out.write("\t\t        \t\t\t\t\t\t<a href=\"1.jpg\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContent.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/thumbnail/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.thumbnail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"\"></a>\r\n");
      out.write("        \t\t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t<div class=\"col-lg-6 col-12\">\r\n");
      out.write("        \t\t\t\t\t\t\t<div class=\"product__info__main\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\r\n");
      out.write("        \t\t\t\t\t\t\t\t<div class=\"product-reviews-summary d-flex\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<ul class=\"rating-summary d-flex\">\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<li><i class=\"zmdi zmdi-star-outline\"></i></li>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<li><i class=\"zmdi zmdi-star-outline\"></i></li>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<li><i class=\"zmdi zmdi-star-outline\"></i></li>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<li class=\"off\"><i class=\"zmdi zmdi-star-outline\"></i></li>\r\n");
      out.write("    \t\t\t\t\t\t\t\t\t\t\t<li class=\"off\"><i class=\"zmdi zmdi-star-outline\"></i></li>\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("        \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t\t\t<div class=\"price-box\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("        \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product__overview\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("        \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t\t\t<div class=\"box-tocart d-flex\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<span>Qty</span>\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<input id=\"quantity\" class=\"input-text qty\" name=\"qty\" min=\"1\" value=\"1\" title=\"Qty\" type=\"number\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t<div class=\"addtocart__actions\">\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t\t<button id=\"btnAddCart\" class=\"tocart\" type=\"submit\" title=\"Add to Cart\">Add to Cart</button>\r\n");
      out.write("        \t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"product-addto-links clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"wishlist\" href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"compare\" href=\"#\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product_meta\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"posted_in\">Categories: \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Adventure</a>, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Kids' Music</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"product-share\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li class=\"categories-title\">Share :</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon-social-twitter icons\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon-social-tumblr icons\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon-social-facebook icons\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon-social-linkedin icons\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t\t</div>\r\n");
      out.write("        \t\t\t\t</div>\r\n");
      out.write("        \t\t\t</div>\r\n");
      out.write("        \t\t\t\r\n");
      out.write("        \t\t</div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End main Content -->\r\n");
      out.write("        <script>\r\n");
      out.write("        \t$(document).ready(function(){\r\n");
      out.write("        \t\t$('#btnAddCart').click(function(e){\r\n");
      out.write("        \t\t\te.preventDefault();\r\n");
      out.write("        \t\t\tvar formData  = new FormData();\r\n");
      out.write("        \t\t\tformData.append('book_id',");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\r\n");
      out.write("        \t\t\tformData.append('quantity',$('#quantity').val());\r\n");
      out.write("        \t\t\tformData.append('price',");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\t\tvar data={};\r\n");
      out.write("        \t        for(var item of formData.entries()){\r\n");
      out.write("        \t            data[\"\"+item[0]+\"\"] =item[1];\r\n");
      out.write("        \t        }\r\n");
      out.write("        \t        addCart(data);\r\n");
      out.write("        \t        \r\n");
      out.write("        \t\t})\r\n");
      out.write("        \t\t\r\n");
      out.write("        \t\tfunction addCart(data){\r\n");
      out.write("        \t\t\t$.ajax({\r\n");
      out.write("        \t\t\t\turl:'/api/addCart',\r\n");
      out.write("        \t\t\t\ttype:'POST',\r\n");
      out.write("        \t\t\t\tdataType : 'json',\r\n");
      out.write("                \t\tcontentType: 'application/json',\r\n");
      out.write("        \t\t\t\tdata : JSON.stringify(data),\r\n");
      out.write("        \t\t\t\tsuccess: function(){\r\n");
      out.write("        \t\t\t\t\tswal(\"\", \"Thêm vào giỏ hàng thành công\", \"success\");\r\n");
      out.write("        \t\t\t\t},\r\n");
      out.write("        \t\t\t\terror : function(){\r\n");
      out.write("        \t\t\t\t\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("        \t\t\t})\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t})\r\n");
      out.write("\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
